### ISSUE TITLE
Module not Found error

### ISSUE THREAD

**Issue by manashegde** [jazeee/react-datetime-bootstrap#21]
I did `yarn add react-datetime-bootstrap` in my react application 
 Later when I try to import the module in my page using `import { DateTime } from 'react-datetime-bootstrap';`

now, am getting below error when I run the application

Module not found: Can't resolve 'react-datetime-bootstrap' in 'D:\MyreactApp\src\containers\Workspace'

**Comment by jazeee** [comment]
It sounds like a problem with your yarn set up or something.  I'd take a look inside node_modules directory and see if the package actually got added correctly.
Alternatively, start a brand new create react app in the root of your directory and just install this package.
Finally, you may have an errant node_modules directory up the tree. Yarn workspace may be messing you up.

**Comment by manashegde** [comment]
Cool ! its working now,,, 

as I was referring npmjs documentation I installed using the command 
`npm install --save react-datetimepicker-bootstrap`, which should have been `npm install react-datetime-bootstrap`
![image](https://user-images.githubusercontent.com/5063167/72330859-3bf7f680-36dd-11ea-9d8b-5e9ca72ada9d.png)

**Comment by jazeee** [comment]
Thanks for looking into this. I've updated the readme.
Sorry for the confusion.
